### ISSUE TITLE
How do i compile this source code to binary linux native apps?

### ISSUE THREAD

**Issue by azispratama92** [anshkumar/yugioh-glaze#1]
Hello my name is Pratama, its been 2 years since i'm migrating into GNU/Linux Os, maybe this is the time to learn something new, can u teach me how to compile the YGO game into native binary apps for Linux?

Thanks for your attention ^ ^

**Comment by anshkumar** [comment]
Install  [Qt](https://www.qt.io/) for linux and compile it.
